# Generated by Django 5.2.4 on 2025-08-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nationality', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('released', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
