# Generated by Django 5.2.4 on 2025-08-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
