services:
  web:
    build: .
    container_name: nfa_app
    ports:
      - 8080:8080
    volumes:
      - ./src:/app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env-prod
  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
      
volumes:
  postgres_db: