# Generated by Django 5.2.6 on 2025-09-22 03:54

import candidates.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=20, unique=True)),
                ('postal_address', models.TextField()),
                ('mobile_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('service', models.CharField(choices=[('fingerprint_analysis', 'Fingerprint Analysis'), ('digital_forensics', 'Digital Forensics'), ('narcotics_analysis', 'Narcotics Analysis'), ('crime_scene_investigation', 'Crime Scene Investigation'), ('firearms_tool_marks', 'Firearms & Tool Marks'), ('dna_forensics', 'DNA Forensics'), ('questioned_documents', 'Questioned Documents'), ('toxicology', 'Toxicology'), ('serology', 'Serology'), ('pathology', 'Pathology'), ('explosives_analysis', 'Explosives Analysis')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to=candidates.models.contact_upload_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the document', max_length=255)),
                ('purpose', models.TextField(blank=True, help_text='Purpose or description of the document')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Add Document',
                'verbose_name_plural': 'Add Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short code or abbreviation e.g. 'NQ (1)'", max_length=20, unique=True)),
                ('title', models.CharField(help_text="Full job post name, e.g. 'Naib Qasid Male (NFAPS-1)'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('html_content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='HTML Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='candidates.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('postal_address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.profile')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('session', models.CharField(max_length=50)),
                ('reporting_time', models.CharField(max_length=20)),
                ('conduct_time', models.CharField(max_length=50)),
                ('venue', models.TextField(blank=True, help_text='Test venue/location', null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_schedules', to='candidates.candidate')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_schedules', to='candidates.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='candidates.profile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
