# Generated by Django 5.2.5 on 2025-08-07 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=20, unique=True)),
                ('postal_address', models.TextField()),
                ('mobile_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short code or abbreviation e.g. 'NQ (1)'", max_length=20, unique=True)),
                ('title', models.CharField(help_text="Full job post name, e.g. 'Naib Qasid Male (NFAPS-1)'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(max_length=50)),
                ('test_date', models.DateField()),
                ('session', models.CharField(max_length=50)),
                ('reporting_time', models.CharField(max_length=20)),
                ('conduct_time', models.CharField(max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_schedules', to='candidates.candidate')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_schedules', to='candidates.jobpost')),
            ],
        ),
    ]
