# Generated by Django 5.2.6 on 2025-09-22 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('application_deadline', models.DateField()),
                ('number_of_positions', models.PositiveIntegerField(default=1)),
                ('salary_range', models.CharField(blank=True, help_text='e.g., 50000-70000 PKR', max_length=50, null=True)),
                ('requirements', models.TextField(blank=True, help_text='Qualifications, experience, skills required', null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, help_text='Any extra info or instructions', null=True)),
                ('status', models.CharField(choices=[('open', 'Open / Active / Published'), ('closed', 'Closed / Filled / Inactive'), ('draft', 'Draft / Pending / Unpublished'), ('expired', 'Expired'), ('on_hold', 'On Hold / Paused / Temporarily Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='candidates.jobpost')),
            ],
            options={
                'ordering': ['-application_deadline'],
            },
        ),
    ]
