# Generated by Django 5.2.5 on 2025-08-10 14:56

import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('service', models.CharField(choices=[('fingerprint_analysis', 'Fingerprint Analysis'), ('digital_forensics', 'Digital Forensics'), ('narcotics_analysis', 'Narcotics Analysis'), ('crime_scene_investigation', 'Crime Scene Investigation'), ('firearms_tool_marks', 'Firearms & Tool Marks'), ('dna_forensics', 'DNA Forensics'), ('questioned_documents', 'Questioned Documents'), ('toxicology', 'Toxicology'), ('serology', 'Serology'), ('pathology', 'Pathology'), ('explosives_analysis', 'Explosives Analysis')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to=candidates.models.contact_upload_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
