# Generated by Django 5.2.6 on 2025-09-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_joblisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='minimum_age',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum age required', null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='minimum_qualification',
            field=models.CharField(blank=True, choices=[('matric', 'Matric'), ('intermediate', 'Intermediate'), ('bachelors', 'Bachelors'), ('masters', 'Masters')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='required_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Required experience in years', null=True),
        ),
    ]
