# Generated by Django 5.2.5 on 2025-08-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testschedule',
            name='venue',
            field=models.TextField(blank=True, help_text='Test venue/location', null=True),
        ),
    ]
