# Generated by Django 5.2.6 on 2025-09-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_joblisting_minimum_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('matric', 'Matric'), ('intermediate', 'Intermediate'), ('bachelors', 'Bachelors'), ('masters', 'Masters')], max_length=20),
        ),
    ]
