# Generated by Django 5.2.5 on 2025-08-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
