# Generated by Django 5.2.6 on 2025-09-23 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_jobapplication_applicationdocument_jobquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.jobapplication'),
        ),
    ]
