# Generated by Django 5.2.5 on 2025-08-16 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_remove_advertisement_image_advertisement_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='candidates.document'),
        ),
    ]
