# Generated by Django 5.2.5 on 2025-08-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_alter_advertisement_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'To Document', 'verbose_name_plural': 'To Documents'},
        ),
    ]
