# Generated by Django 5.2.5 on 2025-08-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_alter_document_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Add Document', 'verbose_name_plural': 'Add Documents'},
        ),
    ]
